### ISSUE TITLE
Teas width

### ISSUE THREAD

**Issue by mikebutts** [ThomasRipplinger/TeaCozy#1]
https://github.com/ThomasRipplinger/TeaCozy/blob/df7c5b3d27166dde5b267d70515186c498c922b6/index.html#L29-L54

![image](https://user-images.githubusercontent.com/8017734/38557092-ee67518e-3c99-11e8-8b3d-fef7435b2998.png)

The flex on this is right, it just needs a width to make it look like spec.

**Comment by tomripp** [comment]
ok, understood, thx
