### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [ThomasRipplinger/TeaCozy#3]
Meets Expectations

Good job on this project it comes close to the spec. The only real issue was the straight line of teas, which can easily be fixed with a width on the div. Other than the tea this code was great, it was neat with proper indentations, great use of flex which was the main goal of this project, proper tags, great job. Next try to challenge yourself by adding a menu, if you need idea try using themeforest.com or your local cafe! Keep up the good work. You might also want a contact form, you can find a easy example to follow on w3schools.com

**Comment by tomripp** [comment]
Mike, thanks for your review, much appreciated
